# Generated by Django 2.2 on 2020-01-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=80)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
