# Generated by Django 2.2 on 2020-01-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200125_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenos',
            name='Tipo_contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactenos',
            name='apellido',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
