# Generated by Django 2.2 on 2020-01-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactenos',
            old_name='Tipo_contacto',
            new_name='tipo_contacto',
        ),
    ]
