"""
Django settings for player1 project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')387nq^h0@e6ut7-2xhw@j9!yu&loq)!x#lkt7p-)*2hf@h2dv'

DEBUG = True

ALLOWED_HOSTS = []
#definiremos donde el usuario será redirigido despues de autenticarse
LOGIN_REDIRECT_URL = '/'
#definiremos donde el usuario será redirigido despues de cerrar sesión
LOGOUT_REDIRECT_URL = '/'
# SECURITY WARNING: don't run with debug turned on in production!

# Application definition

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'crispy_forms',
    'rest_framework',
    'pwa',
    'social_django',
    'fcm_django',
    'baton.autodiscover',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'



SOCIAL_AUTH_FACEBOOK_KEY = "543103676414128"
SOCIAL_AUTH_FACEBOOK_SECRET = "451b130fa415436c0ba35b8ffbb3af02"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'player1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'player1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# imagenes
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#configuracion pwa

PWA_APP_NAME = "Player 1"
PWA_APP_DESCRIPTION = "Aplicacion para ver las novedades de tu tienda favorita de videojuegos Player 1"
PWA_APP_THEME_COLOR = "rgba(93,214,246,1) "
PWA_APP_BACKGROUND_COLOR = "rgba(93,214,246,1) "
PWA_APP_ICONS = [
    {
        'src':'/static/core/img/pac-man.png',
        'sizes':'152x152'
    },
    {
        'src':'/static/core/img/pac-man.png',
        'sizes':'192x192'
    },
    {
        'src':'/static/core/img/pac-man.png',
        'sizes':'512x512'
    }
]
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR,'serviceworker.js')
#fin modificaciones paw

#configuracion notificaciones push
FCM_DJANGO_SETTINGS = {
        "APP_VERBOSE_NAME": "Player1",
         # default: _('FCM Django')
        "FCM_SERVER_KEY": "AAAAUrf83dk:APA91bFGwemhCrcns3zUXr-jDgHj51S55rdL4VTvWlfNx0FTUUL6ewJBx6dnYf0txmOBw3YCKPvB3w06CnsavGh45m8bjlvUgsi4mZyK1_GRlbGulyp0LuY9io3KkBUBThQFIyd8mlLJ",
         # true if you want to have only one active device per registered user at a time
         # default: False
        "ONE_DEVICE_PER_USER": False,
         # devices to which notifications cannot be sent,
         # are deleted upon receiving error response from FCM
         # default: False
        "DELETE_INACTIVE_DEVICES": True,
}
# fin configuraciones 


#Configuracion login con facebook
AUTHENTICATION_BACKENDS = (
'social_core.backends.facebook.FacebookOAuth2',
'django.contrib.auth.backends.ModelBackend',
)